//
//  RefreshTokenTests.swift
//  iOSDropboxTests
//
//  Created by Christopher G Prince on 1/4/21.
//

import XCTest
@testable import iOSDropbox

class DropboxKey: Codable {
    let DropboxAppKey: String
}

class RefreshTokenTests: XCTestCase {
    // I bootstrapped this file by running Neebla, signing in with Dropbox and getting the JSON output generated by the Dropbox sign in.
    let credsURL = URL(fileURLWithPath: "/Users/chris/Developer/Private/iOSDropbox/dropbox.json")
    
    let dropboxKeyURL = URL(fileURLWithPath: "/Users/chris/Developer/Private/iOSDropbox/DropboxKey.json")
    
    var savedCreds:DropboxSavedCreds!
    var signIn:DropboxSyncServerSignIn!
    
    override func setUpWithError() throws {
        let credsData = try Data(contentsOf: credsURL)
        savedCreds = try JSONDecoder().decode(DropboxSavedCreds.self, from: credsData)
        
        let keyData = try Data(contentsOf: dropboxKeyURL)
        let key = try JSONDecoder().decode(DropboxKey.self, from: keyData)
        
        // This does necessary initializations for Dropbox.
        signIn = DropboxSyncServerSignIn(appKey: key.DropboxAppKey)
    }

    override func tearDownWithError() throws {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
    }

    func testRefresh() throws {
        let creds = DropboxCredentials(savedCreds: savedCreds)
        
        let exp = expectation(description: "exp")
        creds.refreshCredentials { error in
            XCTAssert(error == nil)
            exp.fulfill()
        }
        waitForExpectations(timeout: 10, handler: nil)
    }
}
